use academiclease;
DROP TABLE IF EXISTS room_post;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS university_list;
CREATE TABLE user (id INTEGER AUTO_INCREMENT PRIMARY KEY,name VARCHAR(50) NOT NULL,email VARCHAR(50) UNIQUE NOT NULL,password VARCHAR(50) NOT NULL,created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,image_url TEXT NOT NULL);
CREATE TABLE university_list (id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,name VARCHAR(100) UNIQUE NOT NULL,url VARCHAR(100) NOT NULL,created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE room_post (id INTEGER PRIMARY KEY AUTO_INCREMENT,user VARCHAR(50) NOT NULL,university VARCHAR(100) NOT NULL,created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,title TEXT NOT NULL,body TEXT NOT NULL,status VARCHAR(50) NOT NULL,image_url TEXT NOT NULL);