DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS university;
DROP TABLE IF EXISTS room_post;



CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created date NOT NULL
);

CREATE TABLE university_list (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  url TEXT NOT NULL
);


CREATE TABLE room_post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  university_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  status VARCHAR(50) NOT NULL,
  FOREIGN KEY (auser_id) REFERENCES user (id)
  FOREIGN KEY (university_id) REFERENCES university_list (id)
);